setup:
	-git clone https://bitbucket.org/taylor-bsg/bsg_ip_cores.git
	-git clone --recursive https://bitbucket.org/taylor-bsg/bsg_manycore.git

clean:
	rm -rf *.log *.jou *.pb xsim.dir *.wdb

dist_clean: clean
	rm -rf bsg_ip_cores bsg_manycore
